[deps]
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
BinaryBuilderBase = "7f725544-6523-48cd-82d1-3fa08ff4056e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Registrator = "4418983a-e44d-11e8-3aec-9789530b3b3e"
RegistryTools = "d1eb7eb1-105f-429d-abf5-b0f65cb9e2c4"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
squashfs_tools_jll = "eed32e3e-a7c5-5bf9-9121-5cf3ab653887"
